version: '3'

services:
 db:
   image: mariadb
   restart: always
   volumes:
    - ./database/DB.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
    MYSQL_ROOT_PASSWORD: 123456

 adminer:
   image: adminer
   restart: always
   ports:
    - 8081:8080