version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./nginx/public:/usr/share/nginx/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - todo
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  db:
   image: mariadb
   restart: always
   volumes:
    - ./mariadb/DB.sql:/docker-entrypoint-initdb.d/init.sql
   environment:
    MYSQL_ROOT_PASSWORD: ioUTRA
    
  adminer:
   image: adminer
   restart: always
   depends_on:
    - db
   ports:
    - 8081:8080
  
  todo:
    build: ./todo
    volumes:
      - ./todo/SQL.config:/todo/SQL.config
      - ./todo/templates:/todo/templates
    depends_on:
      - adminer